# Configuration for Positive Pair fine-tuning

# Inherit from default configuration
inherit: "config/default.yaml"

# Specific configuration for positive pair strategy
strategy: "positive_pair"

# Training configuration
training:
  epochs: 3
  loss: "CosineSimilarityLoss"
  batch_size: 32
  warmup_ratio: 0.1

# Data configuration
data:
  negatives_per_query: 0 # No negatives for positive pair training
