# Configuration for Positive Pair fine-tuning

# Inherit from default configuration
inherit: "viir/config/default.yaml"

# Specific configuration for positive pair strategy
strategy: "positive_pair"

# Training configuration
training:
  epochs: 3
  loss: "CosineSimilarityLoss"
  batch_size: 16
  warmup_ratio: 0.1
